# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('contactNum', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('areaOfExpertise', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('prefferedLocation', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('teachingExperience', models.IntegerField()),
                ('currentSchool', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('auth12', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
