# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-17 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('presence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('auth12', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('contactNum', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('areaOfExpertise', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('preferredLocation', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=100)),
                ('teachingExperience', models.IntegerField()),
                ('currentSchool', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
    ]
