# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-18 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20170317_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='auth12',
            new_name='accessToken',
        ),
    ]
