# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170318_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=200),
        ),
    ]
