# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170319_1444'),
        ('login', '0008_auto_20170320_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='currentSchool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SchoolUser'),
        ),
    ]
