# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170320_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
