# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 05:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_schooluser_numofteachers'),
        ('api', '0010_teacher_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance_Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('school_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.SchoolUser')),
            ],
        ),
        migrations.RenameModel(
            old_name='Attendance',
            new_name='Attendance_Present',
        ),
    ]
