# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20170325_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_present',
            name='presence',
        ),
    ]
