# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20170325_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='category',
            field=models.CharField(default=b'none', max_length=10),
        ),
    ]
