# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-01 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20170328_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('year_of_passing', models.CharField(max_length=4)),
                ('institute_name', models.CharField(max_length=50)),
                ('supporting_documents', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_instance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Education')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='device_id',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='fingerprint_id',
            field=models.CharField(default=10, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='mac_id',
            field=models.CharField(default=10, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher_education',
            name='teacher_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Teacher'),
        ),
    ]
