# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-10 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TEACHER_ID', models.CharField(max_length=100)),
                ('TEACHER_NAME', models.CharField(max_length=100)),
                ('TEACHER_EMAIL', models.CharField(max_length=100)),
                ('TEACHER_CONTACT_NUMBER', models.IntegerField()),
                ('TEACHER_ENCRYPTED_PASSWORD', models.CharField(max_length=100)),
            ],
        ),
    ]
