# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-12 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(verbose_name='date created')),
                ('phonenumber', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='TeacherLogin',
        ),
    ]
