# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_schoolprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('geo_coord', models.CharField(blank=True, max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='SchoolProfile',
        ),
    ]
