# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-19 10:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20170319_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schooluser', to=settings.AUTH_USER_MODEL),
        ),
    ]
