# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-24 06:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20170320_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='numOfStudents',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='state',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
