# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-25 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_schooluser_numofteachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('district_name', models.CharField(blank=True, max_length=50)),
                ('city_ids', models.CharField(blank=True, max_length=50)),
                ('district_foreign_id', models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.RenameField(
            model_name='city',
            old_name='state_foreign_id',
            new_name='district_foreign_id',
        ),
        migrations.AddField(
            model_name='schooluser',
            name='district',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='district_id',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
