# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-26 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20170326_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooluser',
            name='name',
            field=models.CharField(default='abcdefgh', max_length=50),
            preserve_default=False,
        ),
    ]
