# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-26 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_schooluser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='city_id',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='district_id',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
