# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-28 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20170326_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='timing',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='wifi_zone',
            field=models.BooleanField(default=False),
        ),
    ]
