# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-29 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_auto_20170328_0549'),
        ('login', '0018_auto_20170328_0616'),
    ]

    operations = [
    ]
