# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-03-31 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_auto_20170331_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooluser',
            name='numOfStudentsPrimary',
            field=models.IntegerField(default=114),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='numOfStudentsSeconadry',
            field=models.IntegerField(default=127),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='numOfStudentsSenior',
            field=models.IntegerField(default=162),
        ),
    ]
