# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-01 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20170331_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooluser',
            name='numOfStudentsSeconadry',
        ),
        migrations.RemoveField(
            model_name='schooluser',
            name='numOfTeachers',
        ),
        migrations.AddField(
            model_name='schooluser',
            name='city_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.City'),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='district_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.District'),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='numOfStudentsSecondary',
            field=models.IntegerField(default=359),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='numOfTeachersPrimary',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='numOfTeachersSecondary',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='numOfTeachersSenior',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='schooluser',
            name='state_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.State'),
        ),
        migrations.AlterField(
            model_name='city',
            name='district_foreign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='state_foreign_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='login.State'),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='numOfStudentsPrimary',
            field=models.IntegerField(default=427),
        ),
        migrations.AlterField(
            model_name='schooluser',
            name='numOfStudentsSenior',
            field=models.IntegerField(default=231),
        ),
    ]
